apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80